const mapApartmentToModel = (apartment) => ({
    title: apartment.title,
    subtitle: apartment.subtitle,
    state: apartment.address.state,
    country: apartment.address.country,
    city: apartment.address.city,
    street: apartment.address.street,
    houseNumber: apartment.address.houseNumber,
    zip: apartment.address.zip,
    price: apartment.price,
    guests: apartment.guests,
    bedrooms: apartment.bedrooms,
    bathrooms: apartment.bathrooms,
    propertyType: apartment.propertyType,
    description: apartment.description,
    src: apartment.image.src,
    airConditioning: apartment.amenities.airConditioning,
    heating: apartment.amenities.heating,
    wifi: apartment.amenities.wifi,
    parking: apartment.amenities.parking,
    washingMachine: apartment.amenities.washingMachine,
    dryer: apartment.amenities.dryer,
    dishwasher: apartment.amenities.dishwasher,
    balcony: apartment.amenities.balcony,
    pool: apartment.amenities.pool,
    gym: apartment.amenities.gym,
    elevator: apartment.amenities.elevator,
    petFriendly: apartment.amenities.petFriendly,
    furnished: apartment.amenities.furnished,
    securitySystem: apartment.amenities.securitySystem,
    fireplace: apartment.amenities.fireplace,
    garden: apartment.amenities.garden,
    rooftopAccess: apartment.amenities.rooftopAccess,
    smartHomeFeatures: apartment.amenities.smartHomeFeatures,
    cableTV: apartment.amenities.cableTV,
    outdoorSeating: apartment.amenities.outdoorSeating,
    kitchenAppliances: apartment.amenities.kitchenAppliances,
    smokeDetectors: apartment.amenities.smokeDetectors,
    wheelchairAccessible: apartment.amenities.wheelchairAccessible,
});


export default mapApartmentToModel;