const initialApartmentForm = {
    title: "",
    subtitle: "",
    state: "",
    country: "",
    city: "",
    street: "",
    houseNumber: "",
    zip: "",
    price: "",
    bedrooms: "",
    bathrooms: "",
    propertyType: "",
    description: "",
    imageUrl: "",
    airConditioning: false,
    heating: false,
    wifi: false,
    parking: false,
    washingMachine: false,
    dryer: false,
    dishwasher: false,
    balcony: false,
    pool: false,
    gym: false,
    elevator: false,
    petFriendly: false,
    furnished: false,
    securitySystem: false,
    fireplace: false,
    garden: false,
    rooftopAccess: false,
    smartHomeFeatures: false,
    cableTV: false,
    outdoorSeating: false,
    kitchenAppliances: false,
    smokeDetectors: false,
    wheelchairAccessible: false,
};



export default initialApartmentForm;