const amenities = [
    "airConditioning",
    "heating",
    "wifi",
    "parking",
    "washingMachine",
    "dryer",
    "dishwasher",
    "balcony",
    "pool",
    "gym",
    "elevator",
    "petFriendly",
    "furnished",
    "securitySystem",
    "fireplace",
    "garden",
    "rooftopAccess",
    "smartHomeFeatures",
    "cableTV",
    "outdoorSeating",
    "kitchenAppliances",
    "smokeDetectors",
    "wheelchairAccessible",
];

export default amenities;